(function(){'use strict';let isSubmitting=false;

/* ─── Router: problemset page vs task page ─────────────────────────── */
function init(){if(document.readyState==='loading'){document.addEventListener('DOMContentLoaded',onReady)}else{onReady()}}
function onReady(){let p=window.location.pathname;if(/^\/problemset\/?$/.test(p))injectProgress();else if(/^\/problemset\/task\/\d+/.test(p))injectEditor()}

/* ═══════════════════════════════════════════════════════════════════════
   PART 1 — Problemset Page: Solved / Total Progress
   ═══════════════════════════════════════════════════════════════════════ */
function injectProgress(){if(document.getElementById('cses-progress'))return;let tasks=document.querySelectorAll('li.task');let total=tasks.length;let solved=document.querySelectorAll('li.task span.task-score.icon.full').length;let pct=total>0?Math.round(solved/total*100):0;let nav=document.querySelector('.nav-bar')||document.querySelector('h1')?.parentElement||document.querySelector('h2')?.parentElement||document.body;let div=document.createElement('div');div.id='cses-progress';div.style.cssText='background:#fff;border:1px solid #e0e0e0;border-radius:12px;padding:16px 20px;margin:16px 0;font-family:-apple-system,BlinkMacSystemFont,"Segoe UI",Roboto,sans-serif';
div.innerHTML='<div style="display:flex;justify-content:space-between;align-items:center;margin-bottom:8px">'+
'<span style="font-weight:700;font-size:15px;color:#2b2b2b">\u{1f4ca} Problems Solved</span>'+
'<span style="font-weight:600;font-size:14px;color:#8a8a8a">'+solved+' / '+total+'</span>'+
'</div>'+
'<div style="height:10px;background:#e8e8e8;border-radius:999px;overflow:hidden">'+
'<div style="height:100%;width:'+pct+'%;background:#58cc02;border-radius:999px;transition:width 0.5s ease"></div>'+
'</div>'+
'<div style="text-align:right;margin-top:4px;font-size:12px;color:#8a8a8a;font-weight:500">'+pct+'% complete</div>';
if(nav===document.body)document.body.insertBefore(div,document.body.firstChild);else nav.parentNode.insertBefore(div,nav.nextSibling)}

/* ═══════════════════════════════════════════════════════════════════════
   PART 2 — Task Page: Code Editor
   ═══════════════════════════════════════════════════════════════════════ */
function injectEditor(){let s=document.querySelector('.nav.sidebar');if(!s||document.getElementById('cses-editor-wrapper'))return;let tid=getTaskId();s.innerHTML='';s.style.width='420px';s.style.padding='0 9.6px';s.style.borderLeft='1px solid #000';let w=document.createElement('div');w.id='cses-editor-wrapper';let savedLang=localStorage.getItem('cses_lang')||'C++';w.innerHTML='<div class="cses-ed-head"><span class="cses-ed-dot"></span> Code Editor</div><div class="cses-ed-controls"><label for="cses-language-select">Language</label><select id="cses-language-select"><option value="C++">C++</option><option value="C">C</option><option value="Java">Java</option><option value="Python3">Python</option><option value="Node.js">JavaScript</option></select></div><textarea id="cses-code-textarea" placeholder="Write your code here... (Ctrl+Enter to submit)" spellcheck="false" wrap="off"></textarea><div class="cses-ed-actions"><button id="cses-submit-btn">\u25b6 Submit</button><span id="cses-status-msg"></span></div><div id="cses-result"></div>';s.appendChild(w);let sel=w.querySelector('#cses-language-select');sel.value=savedLang;sel.addEventListener('change',function(){try{localStorage.setItem('cses_lang',this.value)}catch(e){}});let ta=w.querySelector('#cses-code-textarea');if(tid){try{let d=localStorage.getItem('cses_draft_'+tid);if(d)ta.value=d}catch(e){}ta.focus()}ta.addEventListener('keydown',function(e){if(e.key==='Tab'){e.preventDefault();let a=this.selectionStart,b=this.selectionEnd;this.value=this.value.substring(0,a)+'    '+this.value.substring(b);this.selectionStart=this.selectionEnd=a+4}else if((e.ctrlKey||e.metaKey)&&e.key==='Enter'){e.preventDefault();onSubmit()}});ta.addEventListener('input',function(){if(tid){try{localStorage.setItem('cses_draft_'+tid,this.value)}catch(e){}}});document.getElementById('cses-submit-btn').addEventListener('click',onSubmit)}

function getTaskId(){let m=window.location.pathname.match(/\/task\/(\d+)/);return m?m[1]:null}
function getFilename(l){return{'C++':'solution.cpp',C:'solution.c',Java:'Solution.java',Python3:'solution.py','Node.js':'solution.js'}[l]||'solution.txt'}
function getOption(l){return{'C++':'C++20',Python3:'PyPy3'}[l]||''}
function sleep(ms){return new Promise(r=>setTimeout(r,ms))}
function esc(s){return s?s.replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;'):''}

async function fetchCsrf(tid){let r=await fetch('/problemset/submit/'+tid+'/',{credentials:'same-origin'});if(r.redirected||r.url.includes('/login'))throw Error('Not logged in. Please log into CSES first.');let h=await r.text();let m=h.match(/csrf_token" value="([^"]+)"/);if(!m)throw Error('No CSRF token - please log into CSES first.');return m[1]}
async function submitCode(code,lang,tid){let csrf=await fetchCsrf(tid);let fd=new FormData();fd.append('csrf_token',csrf);fd.append('task',tid);fd.append('file',new Blob([code],{type:'text/plain'}),getFilename(lang));fd.append('lang',lang);fd.append('option',getOption(lang));fd.append('type','course');fd.append('target','problemset');let r=await fetch('/course/send.php',{method:'POST',body:fd,redirect:'follow'});return{html:await r.text(),url:r.url}}
async function pollReady(url,html){let st=extractStatus(html);let a=0;while((st==='PENDING'||st==='QUEUE'||st==='')&&a<90){await sleep(2000);let r=await fetch(url);html=await r.text();st=extractStatus(html);a++}return html}
function extractStatus(h){let m=h.match(/<span id="status">([^<]+)<\/span>/);return m?m[1].trim():''}
function parseResult(h){let verdict=extractStatus(h);let vc='';let vm=h.match(/<span class="inline-score verdict ([^"]+)">([^<]+)<\/span>/);if(vm){vc=vm[1];verdict=vm[2]}let ce=null;let cm=h.match(/Compiler report<\/h3>\s*<div>\s*<pre>([\s\S]*?)<\/pre>/i);if(cm)ce=cm[1].trim();let tests=[];let re=/<td class="verdict ([^"]+)">([^<]+)<\/td>/g;let m2;while((m2=re.exec(h))!==null)tests.push({c:m2[1],v:m2[2]});return{verdict,verdictClass:vc,passed:tests.filter(t=>t.v==='ACCEPTED').length,total:tests.length,compileError:ce}}
function verdictStyle(v){let map={ACCEPTED:{color:'#58cc02',icon:'\u2705',label:'ACCEPTED'},'WRONG ANSWER':{color:'#ff4b4b',icon:'\u274c',label:'WRONG ANSWER'},'COMPILE ERROR':{color:'#ff9600',icon:'\u26a0\uFE0F',label:'COMPILE ERROR'},'TIME LIMIT':{color:'#ff4b4b',icon:'\u23f0',label:'TIME LIMIT'},'RUNTIME ERROR':{color:'#ff4b4b',icon:'\u{1f4a5}',label:'RUNTIME ERROR'}};return map[v]||{color:'#8a8a8a',icon:'\u2753',label:v}}

function displayResult(r,div){let d=verdictStyle(r.verdict);let won=r.verdict==='ACCEPTED';let h='<div class="cses-verdict" style="color:'+d.color+'">'+d.icon+' '+d.label+'</div>';if(r.compileError)h+='<div class="cses-compile-error"><pre>'+esc(r.compileError)+'</pre></div>';if(r.total>0){let pct=Math.round(r.passed/r.total*100);let bc=won?'#58cc02':d.color;h+='<div class="cses-test-summary">'+r.passed+' / '+r.total+' tests passed \u00b7 '+pct+'%</div><div class="cses-progress-bar"><div class="cses-progress-fill" style="width:'+pct+'%;background:'+bc+';"></div></div>'}div.innerHTML=h;div.style.borderColor=won?'#58cc02':d.color}

async function onSubmit(){if(isSubmitting)return;isSubmitting=true;let btn=document.getElementById('cses-submit-btn');let st=document.getElementById('cses-status-msg');let rd=document.getElementById('cses-result');let ta=document.getElementById('cses-code-textarea');let ls=document.getElementById('cses-language-select');let code=ta.value.trim();if(!code){rd.innerHTML='<div class="cses-verdict" style="color:#ff9600">\u270f\uFE0F Write some code first</div>';isSubmitting=false;return}let tid=getTaskId();if(!tid){rd.innerHTML='<div class="cses-verdict" style="color:#ff4b4b">\u26a0\uFE0F No task ID found</div>';isSubmitting=false;return}let lang=ls.value;btn.disabled=true;btn.textContent='\u23f3 Submitting';st.textContent='';rd.style.borderColor='#e0e0e0';rd.innerHTML='<div class="cses-verdict" style="color:#8a8a8a;font-size:15px;font-weight:500">\u23f3 Submitting your code...</div>';try{st.textContent='Running...';rd.innerHTML='<div class="cses-verdict" style="color:#8a8a8a;font-size:15px;font-weight:500">\u23f3 Compiling and running tests...</div>';let{html:rh,url:ru}=await submitCode(code,lang,tid);st.textContent='Checking...';let fh=await pollReady(ru,rh);let res=parseResult(fh);displayResult(res,rd);if(res.verdict==='ACCEPTED'&&tid){try{localStorage.removeItem('cses_draft_'+tid)}catch(e){}}st.textContent=''}catch(e){rd.style.borderColor='#ff4b4b';rd.innerHTML='<div class="cses-verdict" style="color:#ff4b4b">\u26a0\uFE0F '+esc(e.message)+'</div>';st.textContent=''}finally{btn.disabled=false;btn.textContent='\u25b6 Submit';isSubmitting=false}}

init()})();
